### PR TITLE
map unsubscribedFromEmails trait to unsubscribed_from_emails

### PR DESCRIPTION
**Pull request by bobjflong**

### CODE REVIEW

**Comment by f2prateek** [comment]
Can you add a link to the docs in the code as a comment?

**Comment by bobjflong** [comment]
done!

**Comment by hankim813** [comment]
@f2prateek @sperand-io are we going to spec the "unsubscribe" event? Because it's getting to a point where a few of our popular tools are getting ad hoc ways to unsubscribe via our API. 

eg. vero, mailchimp

Also -- if we are going to add this feature, we should ask for this Intercom specific trait in the `integrations` object like we do for their secure mode user hash on the server side.

so something like:

```
analytics.identify('<%= current_user.id %>', {
    email   : '<%= current_user.email %>',
    createdAt : '<%= current_user.created %>'
}, {
    integrations: {
        Intercom : {
            unsubscribedFromEmails: true
        }
    }
});
```

Since this is adhoc, would not want this semantic trait to bleed and pollute other tools' data.

**Comment by f2prateek** [comment]
Yeah we definitely should.

**Comment by amburke** [comment]
@hankim813 do you have an idea of when the above suggested changes might be made? Just want to keep a customer of ours in the loop. 

Let me know if there's anything else you might need from our end. Thanks!

**Comment by hankim813** [comment]
@amburke I think we want to spec this event rather than continuing to patch individual integration to support this in this way. 

We'd like to spec an event like `Unsubscribe User` event and map that across all the tools that support such a feature. This will definitely take some time... not sure on the ETA. 

@f2prateek

**Comment by sperand-io** [comment]
I'm okay implementing via `context['Intercom'].unsubscribedFromEmails` for now (traits should still just be `custom_attributes`, but we should also spec some top-level context field for identify calls that signifies subscription status that all the integrations can respect. @hankim813

**Comment by hankim813** [comment]
New PR to reflect changes here #15

**Pull request closed without merging**
